#!/usr/bin/env bash
OPENARM_REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
export PATH="${UV_PROJECT_ENVIRONMENT:-$OPENARM_REPO_ROOT/.venv}/bin:$PATH"
export PYTHONPATH="$OPENARM_REPO_ROOT/src${PYTHONPATH:+:$PYTHONPATH}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-4}"
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export CPU_SET="${CPU_SET:-0-31}"
export TOKENIZERS_PARALLELISM=false
export HF_HOME="${HF_HOME:-$OPENARM_REPO_ROOT/.cache/huggingface}"
export DIFFSYNTH_MODEL_BASE_PATH="${DIFFSYNTH_MODEL_BASE_PATH:-$OPENARM_REPO_ROOT/checkpoints}"
export DIFFSYNTH_SKIP_DOWNLOAD=true
export OPENARM_DATA_ROOT="${OPENARM_DATA_ROOT:-$OPENARM_REPO_ROOT/data/pillow_0702}"
export PYTHONUNBUFFERED=1
